@startuml



class Observable{
    +RegisterObserver()
    +UnregisterObserver()
    +NotifyObservers()
}

note top of Observable : Subject



class CGameSettings {
    -m_stretchMode
    +StretchMode()
    +SetStretchMode()
}

note left of CGameSettings : ConcreteSubject

class Observer {
    +Notify()
}

note top of Observer : Observer

class GUIGameSettings {
    -m_renderSettings
    +Notify()
}

note right of GUIGameSettings : ConcreteObserver



Observable <|-- CGameSettings
Observable -> Observer
Observer <|-- GUIGameSettings
CGameSettings <- GUIGameSettings

@enduml