@startuml


class CGenericTouchActionHandler {
    - CGenericTouchActionHandler()
    + static GetInstance() : CGenericTouchActionHandler&
}

note top of CGenericTouchActionHandler : Singleton
@enduml